name: "My actions"
description: "Test"

inputs:
 message:
  description: "The message to display"
  requiered: true
  default: "Hola"

runs:
 using: "composite"

 steps:
 - name: Hola
   run: echo "${{inputs.message}}, mundo!"
   shell: bash