name: Hola mundo!!!

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - user

jobs:

  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Print "Hola mundo!!!"
      run: echo "Hola mundo!!!"

    - name: touch file
      run: touch hello.txt

    - name: Set text
      run: echo "hola mundo" >> hello.txt

    - name: Read file
      run: cat hello.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: List
      run: ls -la

    - name: prueba
      run: ls -l 

# Comentario de user


#  build:
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Build Docker image
#