name: Hola mundo!!!

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Print "Hola mundo!!!"
      run: echo "Hola mundo!!!"
  other:
    runs-on: ubuntu-latest

    steps:
    - name: List
      run: ls -la
      
#  build:
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Build Docker image
#