name: variable

on: [push, pull_request]

jobs:
    var:
        runs-on: ubuntu-latest

        env:
            MY_VAR: Mi variable de entorno

        steps:
            - name: Var
              run: echo "Valor $MY_VAR"
